spring:
  main:
    web-application-type: none
  application:
    name: mihomo_auto_proxy
logging:
  config: classpath:./logback-spring.xml
  file:
    path: ./logs
  level:
    dao: info
server:
  port: 18034
mihomo:
  api:
    base-url: http://127.0.0.1:9090
    secret: set-your-secret
